export const FETCH_DEVELOPERS_START = "FETCH_DEVELOPERS_START";
export const FETCH_DEVELOPERS_SUCCESS = "FETCH_DEVELOPERS_SUCCESS";
export const FETCH_DEVELOPERS_FAILURE = "FETCH_DEVELOPERS_FAILURE";

export const FETCH_CURRENCY_START = "FETCH_CURRENCY_START";
export const FETCH_CURRENCY_SUCCESS = "FETCH_CURRENCY_SUCCESS";
export const FETCH_CURRENCY_FAILURE = "FETCH_CURRENCY_FAILURE";

export const POST_FAVORITES = "POST_FAVORITES";